# Generated by Django 4.1.4 on 2022-12-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
