# Generated by Django 4.1.4 on 2022-12-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0002_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='downvote',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='upvote',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='downvote',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='upvote',
            field=models.IntegerField(blank=True),
        ),
    ]
